# Generated by Django 5.2.1 on 2025-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("venue", models.CharField(max_length=100)),
                ("dicription", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
