# Generated by Django 5.2.1 on 2025-05-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="dicription",
            new_name="description",
        ),
    ]
